### ISSUE TITLE
Make import/export from clipboard compatible with import/export from file

### ISSUE THREAD

**Issue by breakline87** [mockoon/mockoon#102]
**Describe the bug**
I got an exported file from another developer, but when I import it, nothing happens, no error message, nothing.

**Mockoon version:**
1.3.0

**OS / OS version:**
MacOS on one machine, Windows10 on another

**Comment by axc450** [comment]
Do you have the exported JSON (or an example) that doesnt import?
Does this happen just for you/can other people import it?

**Comment by ickybodclay** [comment]
Same is happening to me.

Created file on Windows version of Mockoon by right clicking on environment and clicking "Copy to clipboard (JSON)" and saving to a file, cannot import on Mac version of Mockoon using import all environments from file.

However importing from clipboard by opening the file, selecting all, and copy works.  I think the issue is that import ALL environments has slightly different JSON than the individual environment and there is some confusion between functionality.  I expected import from file to just import the one environment, but it appears that the only way to import a single environment is the clipboard copy?  I think just clarifying import wording and maybe having separate import/export for single environment vs all.

**Comment by 255kb** [comment]
@ickybodclay I think these features need clarification. Import from file is not compatible yet with import from clipboard. maybe it should. 

I will rename the ticket to reflect this, and improve compatibility with different import features.
