### ISSUE TITLE
Save request to file

### ISSUE THREAD

**Issue by m4ss1m0g** [mockoon/mockoon#1027]
Allowing to save a request to a json/txt file can open integrating Mockoon to other software.

Sometimes it happens that I have to update a single field in a database in response to a request; with a saved request I can develop a simple program to monitor a folder and read the txt to update the field.

The option to respond with a file is already implemented; with the saved file feature I can use Mockoon as an interface with other software to fake data.

**Comment by 255kb** [comment]
Since v4.0.0 was released today, I would advise that you take a look at how logs are [now saved by the desktop application in JSON](https://mockoon.com/releases/4.0.0/#desktop-application). You may be able to parse them.

If this is not enough to solve your use case, I suggest that you upvote [this issue](https://github.com/mockoon/mockoon/issues/1045). I will be closing this one as a duplicate.
