### ISSUE TITLE
dataRaw not getting raw data anymore

### ISSUE THREAD

**Issue by yohny** [mockoon/mockoon#1050]
**Describe the bug**

`dataRaw` helper can be used used to get raw data from a bucket for further processing, but its broken now (used to work as expected in v1.22.0)
I have a data bucket called `seed` defined like this
```json
{
  "categories": ["A", "A1","B", "B1", "C", "C1", "D", "D1", "F", "G", "M", "SA", "SB", "SC", "SD", "SE"],
  "types": ["TZ", "PP", "PK"],
  "cantons": ["LU", "AG", "SH", "ZG" ]
}
```
and in template I use the following to get random canton `{{oneOf (dataRaw 'seed' 'cantons')}}` - this used to work until 1.22.0, but now it just returns single characters of the stringified array (I guess), for example `&quot;` or `C`

**To Reproduce**

create a data bucket containig array property and try the above template to get a raw value out of it

**Mockoon version:**

3.0.0

**OS / OS version:**

Windows 10

**Comment by 255kb** [comment]
I just tested with v3.0.0 with the exact JSON and template you provided and it works. I correctly get one of the cantons entries ("LU", etc.). 
Could you maybe [share your entire environment JSON file](https://mockoon.com/docs/latest/mockoon-data-files/environment-clipboard-copy/#copy-an-environment-or-a-route-json-to-the-clipboard) so I can see if there an error somewhere?

**Comment by yohny** [comment]
I found the rootcause of the issue - the databucket contained invalid json and that resulted in wrong template output. Originally I posted incomplete databucket, here is the full version:
```json
{
  "categories": ["A", "A1","B", "B1", "C", "C1", "D", "D1", "F", "G", "M", "SA", "SB", "SC", "SD", "SE"],
  "types": ["TZ", "PP", "PK"],
  "cantons": ["LU", "AG", "SH", "ZG" ]     // missing comma after the array
  "licensePlateSE": ["CD", "CC", "H", "Z", "ZM"]
}
```
I guess JSON validation of databucket(s) would help avoid such hard-to-debug errors.

**Comment by 255kb** [comment]
I suspected something like this. We definitely need to improve the reporting of JSON errors in the various editors.

**Comment by brano-p** [comment]
Hello there, funny - I've found this issue of @yohny (actually a colleague of mine) after a couple of years because we've had a very similar problem, this time with an excess comma at the end of the last member of the JSON object, i.e.:

```json
{
  "categories": ["A", "A1","B", "B1", "C", "C1", "D", "D1", "F", "G", "M", "SA", "SB", "SC", "SD", "SE"],
  "types": ["TZ", "PP", "PK"],
  "cantons": ["LU", "AG", "SH", "ZG" ],
  "licensePlateSE": ["CD", "CC", "H", "Z", "ZM"],
}
```
It seems to me that this issue is still present - there was no apparent validation of the data, it just quietly fails and returns an empty string. I'm also wondering why the excess coma is considered as invalid, but that's off topic.

This is with Mockoon 9.3.0 - i.e. currently the latest version.

**Comment by 255kb** [comment]
JSON templates validation is a recurring issue which, due to the templating system being used a bit everywhere, is not easy to address (it will probably as part of #1393). 

Tha being said, for data buckets there is now a [live view of the generated JSON](https://mockoon.com/releases/9.1.0/#improved-data-buckets-state-reporting) with validation, where you can typically see this kind of errors. 

Lastly, trailing commas are and were always invalid in JSON.
