### ISSUE TITLE
Large response throws JSON Parse error or no value at all

### ISSUE THREAD

**Issue by sustepavkentico** [mockoon/mockoon#122]
Hi, 
your tool is pretty awesome. However, we are facing this issue.

When the mocked response is a JSON with the length of about 260000+ rows, Mockoon returns JSON PARSE error if the content type is set to Json and 200 with no value at all, if the content type is set to plain text. There is probably some problem with the Dummy Json parser. 

Could you please look into this or at least come with the possibility of turning of the JSON parser?

Thank you for your response.

**Comment by 255kb** [comment]
Tested with a 350 000 lines file with 233 333 `body` template helpers. A call uses around 4Gb of ram and takes 40 seconds to execute. Apparently there is a memory leak in Dummy-json (or handlebars?). Replacing by a simple regex reduces memory usage to less than 100Mb with 500ms execution time. 

This probably needs to be tackled together with #253 which plan to change the templating engine to something else in order to improve JSON linting.

**Comment by 255kb** [comment]
@sustepavkentico Could you please provide an example of the problematic JSON? I am benchmarking libraries and would need real world example if possible. Thank you!

**Comment by 255kb** [comment]
After doing several tests it appears that the more helpers you add in the body the more memory is consumed during the call. This is apparently linked to the way Handlebars handle helpers. As I decided to stick with Handlebars for the templating (#253) I won't be able to solve this issue directly. 

So, as you suggested I will add an option to disable templating on each route response #129
