### ISSUE TITLE
Create routes from proxy responses

### ISSUE THREAD

**Issue by gabrielperes97** [mockoon/mockoon#139]
When I'm mocking a api, firstly I run my app proxied and so I copy the data from the log to a new route.

It can be helpful a button on the route of the environment log to use that request/response as a mock.

**Comment by gabrielperes97** [comment]
It can be developed more enhanched after the Issue #138 . I want to work in both.

**Comment by 255kb** [comment]
Could you please clarify what you mean by "proxy". Because Mockoon also has a "proxy" feature which redirect all non declared routes to a URL you provide (in the environment settings). 

Specifications I understand from your ticket are the following: 
- you create an environment / declare some routes.
- when you call this environment you can see all the entering requests in the "environment logs" tab. Some are caught by declared routes, some not (green tick or not). 
- on entering requests not caught (without green tick) you can have a button allowing one to declare the route automatically from entering request characteristics. 

Am I right? 

For your information, I started working on #75 in which I have to change many things because the route model changed. There is now a `responses` array containing multiple responses for each route. Also the store behavior changed as more UI options are required (multiple responses tabs, etc). 
If you start working on this feature you may need to rewrite part of your code after my branch is merged. It's not published yet, I have it locally only but I can push something soon. I worked quite a lot on it so it has good chances to be merged soon.

**Comment by gabrielperes97** [comment]
You are right. This is it.

I'll work on #138 first until you merge #75.

**Comment by 255kb** [comment]
ok it's probably better and easier to wait on #75 
Thank you
