### ISSUE TITLE
Ability to display relative dates instead of absolute dates

### ISSUE THREAD

**Issue by nagromc** [mockoon/mockoon#1430]
In the _Logs_ tab, I need to do some mental computation to determine if the latest logged request has just been received or if it is older.

It could be great to have the ability to display relative dates instead of absolute dates. Something like _just now_, _42 minutes ago_, _2 hours ago_, or _Yesterday 13:37_.

Maybe a toggle in the _Logs_ tab could be the best place to switch back and forth easily between the two modes?

**Comment by 255kb** [comment]
That's a nice idea! 

I suggest this implementation for whoever wants to work on this: 

- Make the timestamp clickable, maybe with a tooltip "Relative time format" / "Absolute time format"
 
  ![image](https://github.com/mockoon/mockoon/assets/7489814/59a42ce7-6849-4605-9094-4ac280fff06a)

- save this in an application setting, `displayTimeFormat`
- add a checkbox in the settings modal "Use relative time for timestamps"

**Comment by 255kb** [comment]
📦 This was released in [v8.4.0](https://mockoon.com/releases/8.4.0/)

**Comment by bcatelin** [comment]
How can we disable that feature and switch back to the absolute time format? having to hover over each log entry is not practical.
I am not sure why people would prefer to see the human readable format, but OK. However, I am keeping an older version of mockoon just because of that. Right now, I am developping an API client and uses Mockoon for what it is for: mocking the API. I have introduced sleeps for various reasons and I need to see if they are well implemented, we are talking ms here. To see 5 calls with 'less than a minute ago' is not usefull.
