### ISSUE TITLE
MacOS Icons aren't in line with the rest of the system

### ISSUE THREAD

**Issue by DavidTheProgrammer** [mockoon/mockoon#1500]
This is a very minor issue but I think it'll be good to have the Mockoon icons match the rest of the system. Including the app switcher 

<img width="686" alt="image" src="https://github.com/user-attachments/assets/0216e2a9-a828-4f64-8328-a38f16667184">

**Comment by 255kb** [comment]
I'm not sure what you are referring to, maybe the fact that the eyes are not eclosed in a square? 
But I'm not convinced. The logo is the same since more than 7 years and it was never an issue. Also, even if it seems that there is a consensus around square-enclosed logos with rounded corners, looking a bit on google images it seems that it's far from being always true: 
![image](https://github.com/user-attachments/assets/f5b2c116-b292-499e-87e4-57163255756e)

I think we will stick we the unique "staring-at-you-eyes-logo" for the future :)

**Comment by DavidTheProgrammer** [comment]
> I'm not sure what you are referring to, maybe the fact that the eyes are not eclosed in a square? 
> But I'm not convinced. The logo is the same since more than 7 years and it was never an issue. Also, even if it seems that there is a consensus around square-enclosed logos with rounded corners, looking a bit on google images it seems that it's far from being always true: 
> ![image](https://github.com/user-attachments/assets/f5b2c116-b292-499e-87e4-57163255756e)
> 
> I think we will stick we the unique "staring-at-you-eyes-logo" for the future :) 



I'm sorry I didn't add enough context. Yes, what I meant was the fact that the eyes were not in a square like the rest of the icons with rounded borders. 

Thanks for addressing my very minor concern, I understand your position. cheers 👍🏾
