### ISSUE TITLE
multiple route responses

### ISSUE THREAD

**Issue by lucasdealmeida** [mockoon/mockoon#154]
**Is your feature request related to a problem? Please describe.**
I would like to enable or disable the response that I want to receive. Sometimes we are using a third party library and we can't change any data in the request.

**Describe the solution you'd like**
Just a checkbox to say if the response is enable

**Additional context**
I'm using the multiple response feature that was committed a few days ago, I saw the rules in each response, it is a really nice feature.

**Comment by 255kb** [comment]
The implementation you are using (#75 ) already have this feature. But it is not yet published nor documented. It will be part of 1.5.0 and will have a tutorial on the website. 
In order to return a specific response without defining rules you can simply reorder the responses in the dropdown menu. The first one will be the one served by default if no rules are provided, or no rules are matched.
I hope this solves your problem. 
If not do not hesitate to give feedback as it is not yet public and can still be slightly modified.
