### ISSUE TITLE
Accessing variables outside loop scope

### ISSUE THREAD

**Issue by WouterCypers** [mockoon/mockoon#1588]
**Describe the bug**

Local variables set using `setVar` inside a loop, are not accessible outside the loop scope. I found [a pull request](https://github.com/mockoon/mockoon/pull/805) solving a problem where `setVar` didn't work at all inside `#each`, but this seems unrelated at first glance.

**Steps to Reproduce**

Both of the examples below result in empty output, while they should produce "someValue" and "anotherValue" respectively.

```hbs
{{#each (array 'one' 'two' 'three')}}
  {{~setVar 'someVar' 'someValue'~}}
{{/each}}

{{@someVar}}
```

```hbs
{{#repeat 5}}
  {{~setVar 'anotherVar' 'anotherValue'~}}
{{/repeat}}

{{@anotherVar}}
```

A way around this issue would be to use global variables inside a loop and re-assigning it to a local variable (if necessary), but this is hacky and could result in some undefined behavior:
```hbs
{{#each (array 'one' 'two' 'three')}}
  {{~setGlobalVar 'someVar' 'someValue'~}}
{{/each}}

{{~setVar 'someVar' (getGlobalVar 'someVar')~}}
{{~setGlobalVar 'someVar' null~}}

{{@someVar}}
```

Environment file: [issue-variable-outside-loop.json](https://github.com/user-attachments/files/17773203/issue-variable-outside-loop.json)

**Mockoon version:**

9.0.0

**OS / OS version:**

macOS 15.1

**Comment by 255kb** [comment]
I wouldn't say this is a bug.
The `each` block helper creates a new scope. We made sure that the `setVar` creates variable scoped to this block, instead of creating the variable at the root level of the template. 

The alternative is to use the `setGlobalVar` helper. Please note that the `getGlobalVar` helper has a default value that you can provide as the third parameter (it's missing in the docs, I will fix this):

```handlebars
{{getGlobalVar 'varname' null 'defaultvalue'}}
```
