### ISSUE TITLE
Random status code

### ISSUE THREAD

**Issue by zamarrowski** [mockoon/mockoon#159]
In my team we need to get random status code to try some use cases. 

The idea is simple, select many status codes and return one of them randomly.

**Comment by 255kb** [comment]
A new random response option is available since v1.11.0
![image](https://user-images.githubusercontent.com/7489814/110084814-ab70ef80-7d90-11eb-92f8-b7f2f8021e1b.png)
It's not giving you a random status code per se, but rather randomize among the different responses you create. 
I will consider this issue solved for now, and reassess if there is more interest.
