### ISSUE TITLE
Add ability to use own SSL cert or issue it automatically

### ISSUE THREAD

**Issue by dm3ch** [mockoon/mockoon#175]
**Is your feature request related to a problem? Please describe.**
Sometimes I am using mockoon to replace mock some real servers. I'm changing /etc/hosts to make domain name resolves to localhost. Suddenly some apps requires https, in such case I need to setup separate https proxy cause built in cert could be used only for localhost

**Describe the solution you'd like**
It would be cool to have ability to use own (selected) certificate for environment

**Comment by mokkun** [comment]
I ran into this issue with Android; the system does not recognize the self-signed certificate as valid. It would be great if I could provide Mockoon an existent certificate, or if I could at least extract the certificate used by it, so I can add it to the list of trust.

**Comment by RyuSLunK** [comment]
I'm currently getting around this by adding https://github.com/mockoon/mockoon/blob/master/src/app/ssl.ts to my keychain access on mac. Just create a mockoon-cert.pem, add the .cert part of the ssl.ts to the file. Add the file to keychain access. Get Info and expand trust, trust always. Not ideal for me though because I already have a key-cert I'm using on my client that is trusted. And I also proxy locally through localhost.local. This cert in the ssl is signed for localhost and not localhost.local. If I could simply specify in the environment settings of mockoon that I want to use my own key-cert that'd be helpful!

**Comment by eloo** [comment]
Are there any updates here? 
Is there any tutorial how the used certificate can be added to trusted certificates?

**Comment by 255kb** [comment]
@eloo This is planned and should be available in the coming months.
Also, there is no official tutorial to add the self-signed certificate to your local trusted certificates. You can find the self signed cert [here](https://raw.githubusercontent.com/mockoon/commons-server/main/src/constants/ssl.constants.ts)

**Comment by 255kb** [comment]
@azsoncini Unfortunately, I think I d'ont have this anymore. The [self signed certificate](https://raw.githubusercontent.com/mockoon/commons-server/main/src/constants/ssl.constants.ts) is quite old (~2017) and at that time I didn't thought this through. 
However, I (finally) started working on this task and it should be available in the next update.
