### ISSUE TITLE
Application Freezing After Making One Request

### ISSUE THREAD

**Issue by briannajdhall** [mockoon/mockoon#203]
**Describe the bug**
I am using Mockoon version 1.5.1 on a Mac with macOS Catalina version 10.15. My environment consists of 10 routes (6 GET, 2 POST, and 2 PUT). Within my API flow, I can run approximately two GET requests before the interface freezes, preventing me from being able to make changes. 
My coworker is using the same environment that I am, but he is using a Mac with macOS Mojava 10.14.6. He is having no trouble with freezing.

**To Reproduce**
Load an environment in Mockoon, place a GET request, go back to the user interface, Mockoon is frozen.
Unfortunately, I cannot provide a copy of the environment per my employer.

**Expected behavior**
The application should not freeze upon submitting a request

**Screenshots**
I don't think this would help since the screen is just frozen.

**Mockoon version:**
1.5.1

**OS / OS version:**
macOS Catalina v. 10.15

**Comment by 255kb** [comment]
May be related to entitlements: https://github.com/electron-userland/electron-builder/issues/4040
Need to test with Electron Builder defaults

**Comment by TMUNYU** [comment]
Got this issues too. 1.5.1 on Windows 10

**Comment by 255kb** [comment]
@TMUNYU If this is not specific to one OS, could you please provide your Mockoon's data file? Maybe something is wrong and I could have a look.

**Comment by TMUNYU** [comment]
@255kb So I cannot either. Work advised against due to some sensetive data. I can reproduce this now though. 

The issue happens when I run multiple proxied GETs in quick succession. In my case only one of those GETs is not defined in my routes so it tries to fetch it from the host. It seems that the call itself actually works just fine (I can see some logs on the history window). It is when I try to click any elements on the screen that it freezes. I can actually make 1 or 2 clicks before the freeze (specifically on the routes).

I looked in to the code yesterday and debugged. This is arising (may not be originating) from server.service.ts. This is from the line 

`self.store.update(logResponseAction(environment.uuid, response));`

When the freeze happens I get this error:

`zone-mix.js:396 (node:16436) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit`

Noticed that this code went in for version 1.5.0 which is when I started getting the issue. 

I can continue to try and pinpoint the issue when I have time tonight unless the issue is obvious to you now. 

I hope this helps

**Comment by TMUNYU** [comment]
Just updates to 1.6.0 and problem seems to have gone away

**Comment by 255kb** [comment]
@TMUNYU This helps a lot thank you. 
Please let me know if this is definitely solved for you with 1.6.0
Big changes in 1.5.0 was Electron +5 migration (apparently a lot of things changed). And yesterday I update Electron to version 7 which maybe solved the problem.

@briannajdhall could you please test also with v1.6.0 and confirm that this is working for you?

**Comment by TMUNYU** [comment]
I can confirm now that this issue is fixed @255kb. Have been it for a week now with no issues on version 1.6.0

**Comment by 255kb** [comment]
Thank you for testing @TMUNYU
