### ISSUE TITLE
Ignore rules and default response, return selected response instead

### ISSUE THREAD

**Issue by 255kb** [mockoon/mockoon#252]
**Is your feature request related to a problem? Please describe.**
-Setting the default route response when no rules are matched is not straightforward. A drag and drop is needed to move it to the top of the dropdown
- There is no way to force Mockoon to select a route response without interpreting the rules. This response could also be different from the default one. 

**Describe the solution you'd like**
We need to add a system (checkboxes, etc) to be able to easily tell Mockoon:
- this is the default response when no rule is matched
- this is the response I want to force from now on (without consideration of the default one)

**Additional context**
/!\ UI needs to be clever and easy to use

---

_Original message:_

Currently there is a possibility to set response as a default (by dragging item in the responses list), but I see very useful option to "Ignore rules and default response", and return currently selected response from requested route. 

Usage example:
I have a lot of different responses from one route, but each response have the same rules. From my perspective, I want to be able to simply choose which response should be currently returned by route (IMO, the best option is currently selected response, not default). 

Currently to achieve this, I have to change default response each time. It would be awesome to have it simpler.

Thx for a great tool I use almost each day!

_Originally posted by @aantoniv in https://github.com/mockoon/mockoon/issues/191#issuecomment-566263943_

**Comment by ninjaneer164** [comment]
hi @255kb , one of our teams needed the "ignore default response" feature, so i have that one covered. basically, if none of the responses match, ignore the default response, and instead switch to proxy mode. i realize that this is different from what this ticket is stating, but that's what our team needed, so that's what i have thus far.

i would love to be able to implement the rest of this ticket and create a PR.

let me know!

PS: this is my first time contributing (to any projects!), and i'm trying to follow what you have in CONTRIBUTING.md... let me know if i'm not going about this the right way.

**Comment by 255kb** [comment]
Hi @ninjaneer164! of course any contribution is welcome but I would like to keep the scope of each ticket as small as possible. Also, contributions should be discussed in an issue first. 
The reason is the following: Mockoon should stay simple and easy to use, which is not always easy with contributions that fulfill a very specific need. All requests and contributions may not be accepted and, they need to be prioritized among all the opened issues. 
By reading your proposal, I have the feeling that it's quite an odd feature. Proxy mode is at route level, while route responses are "triggered" or "chosen" when the entering request already matched a route. Reverting to route level when responses level was already reached does not feel right. But I am open and I would be glad to discuss this feature (and your implementation) with you in a separated issue 😃

**Comment by ninjaneer164** [comment]
@255kb done - https://github.com/mockoon/mockoon/issues/278

**Comment by barefootdeveloper** [comment]
I was curious if this interface change might make changing the default request easier.

![Snag_749614a](https://user-images.githubusercontent.com/3580448/118264940-7ebf0f80-b486-11eb-92e5-674a5b829f93.png)

Clicking the outlined flag would change it to the default response and move it up the list.

The other thing I thought of was a checkbox on the route settings page, but this feels a little more discoverable to me.

I realize this doesn't solve the 2nd half of the issue, but that feels like a bigger feature to me.

**Comment by 255kb** [comment]
@barefootdeveloper yeah there are two issues here, and they have to play nicely together, so that's why I didn't split until now:

1. get rid of the drag and drop to define the default response. Your flag idea is interesting, maybe the flag could appear only when hovering the responses and stay visible after a click (without reordering the responses). 

2. Select a response to return no matter what, disabling rules and default response. Adding another UI element like radio buttons, checkboxes, or another icon feel awkward. Maybe the flag could be reused, and a second click on it could make it red, which would force this response. But this is not easily discoverable.

**Comment by barefootdeveloper** [comment]
Yeah @255kb that makes complete sense.

I plan to make another discussion that I think may help fill this need, but they seem like they could be big bodies of work, so I didn't know if there was value in solving the easy half of this. The high-level concepts are:

1) Response Stacking. The idea being you define multiple responses with the same rules and it chooses between those responses. (random, sequential, sequential-loop, etc). This could be done with fairly minimal interface changes, but if you had to change the rules, it could become repetitive so that idea may benefit from interface changes.

2) Interactive Mode. Similar to tools like Burp Suite and Fiddler that allow you to configure your traffic to go through a proxy and intercept and modify requests and responses before they're returned to the requester. If we did something similar here where when interactive mode is enabled (maybe enable it on a route by route basis) it pauses before sending the response and displays the user the proposed response we could allow them to select a different response before returning it. So rather than having them change the routing rules when they want to do these overrides we just turn it into a real-time decision.

**Comment by barefootdeveloper** [comment]
How does this work for you? It's not quite what you described as it closes the drop-down and moves the item, but I think it's the minimal change. Close enough? To do the other approach we'd have to either alter the way the default path is identified or give the dropdown its own state so the underlying application could be re-ordered without changing the dropdown order.

![19C60530-AB1C-43BA-8D92-93B6015C0C22](https://user-images.githubusercontent.com/3580448/118347993-46b2dd80-b515-11eb-9179-80e6ea1d1dd0.GIF)

**Comment by 255kb** [comment]
> Yeah @255kb that makes complete sense.
> 
> I plan to make another discussion that I think may help fill this need, but they seem like they could be big bodies of work, so I didn't know if there was value in solving the easy half of this. The high-level concepts are:
> 
> 1. Response Stacking. The idea being you define multiple responses with the same rules and it chooses between those responses. (random, sequential, sequential-loop, etc). This could be done with fairly minimal interface changes, but if you had to change the rules, it could become repetitive so that idea may benefit from interface changes.

--> I think this get addressed, at least partially, in the latest update with sequential responses and request index rule.

> 2. Interactive Mode. Similar to tools like Burp Suite and Fiddler that allow you to configure your traffic to go through a proxy and intercept and modify requests and responses before they're returned to the requester. If we did something similar here where when interactive mode is enabled (maybe enable it on a route by route basis) it pauses before sending the response and displays the user the proposed response we could allow them to select a different response before returning it. So rather than having them change the routing rules when they want to do these overrides we just turn it into a real-time decision.
--> I saw your new discussion, I will follow up there :)

**Comment by 255kb** [comment]
> How does this work for you? It's not quite what you described as it closes the drop-down and moves the item, but I think it's the minimal change. Close enough? To do the other approach we'd have to either alter the way the default path is identified or give the dropdown its own state so the underlying application could be re-ordered without changing the dropdown order.
> 
> ![19C60530-AB1C-43BA-8D92-93B6015C0C22](https://user-images.githubusercontent.com/3580448/118347993-46b2dd80-b515-11eb-9179-80e6ea1d1dd0.GIF)

I think this could work. But without the dropdown closing and without reordering. 
After re-reading this issue for the nth time I think what could be a good compromise could be the following: 
- keep the responses drag and drop to reorder the responses, but this has not effect on the default response served
- a clickable flag like @barefootdeveloper demoed above, to choose the default response to be served when no rule matches, or when no rule is declared
- a new button to temporarily disable the rules and serve the default "flagged" response

I think we would cover most cases without having to design a confusing UI with many similar options (default response vs forced response).

**Comment by barefootdeveloper** [comment]
I'd like to work on the default route FLAG ui portion of this.

**Comment by 255kb** [comment]
@barefootdeveloper great! 
So this issue will cover this: 
- we keep the responses drag and drop to reorder the responses, and define the rules interpretation order, but this has no effect on the default response anymore
- we add a clickable flag to choose the default response to be served when no rule matches, or when no rule is declared

I created a new issue #498 for the "disable rules temporarily" feature.

**Comment by barefootdeveloper** [comment]
I have the default response migration / backend and flags working in the interface as I would expect but unit testing the flags is turning out to be quite difficult. How do you feel about me adding an additional way to set the default response by adding a checkbox under settings? That would allow us to pretty easily unit test the overall functionality while keeping the convenience of the flags.

I was thinking something like this
![image](https://user-images.githubusercontent.com/3580448/121792360-c5a53f80-cbc1-11eb-8067-a713261185b2.png)
Checking it here would update the flags of course.  Unchecking it would switch the default to the first response (the checkbox would be disabled if there is only one response). 

I'm also thinking of disabling the flags/checkbox whenever sequential or random mode is set, How does that feel?

Here's a GIF of the flags.

![5DFAF125-8BB2-459E-B874-45ADDD424357](https://user-images.githubusercontent.com/3580448/121792398-3b111000-cbc2-11eb-938a-77825749a150.GIF)


A biproduct of this work is that the dropdown stays open when re-ordering items via drag and drop so I think that's a UX win as well.

**Comment by 255kb** [comment]
> I have the default response migration / backend and flags working in the interface as I would expect but unit testing the flags is turning out to be quite difficult. How do you feel about me adding an additional way to set the default response by adding a checkbox under settings? That would allow us to pretty easily unit test the overall functionality while keeping the convenience of the flags.
> ...
> Checking it here would update the flags of course. Unchecking it would switch the default to the first response (the checkbox would be disabled if there is only one response).

I would prefer avoiding this for two reasons: 
- adding UI elements for testing purpose feels awkward
- having two ways to set the default response in two different places will be confusing. It's already a hassle to explain the drag and drop + flag behavior. Also reverting to default = first would be even more confusing. There should be only one way of defining the default, with the flag. 

Regarding testing, what is a problem exactly? I know that I never succeded to test the drag and drop, it just doesn't work. However, hovering the response and clicking the flag should work using maybe `moveTo()` + `click()`. Let me know if you want that I have a look at this. 

> 
> I'm also thinking of disabling the flags/checkbox whenever sequential or random mode is set, How does that feel?

You are right, some visual clue could be useful. But then I would prefer changing the flag's color to grey instead of removing.

**Comment by barefootdeveloper** [comment]
Okay, I'll change the flag to grey whenever those modes are enabled and you'll still be able to interact with them.

I attempted to use moveTo() + click() but I got the error "element not interactable". I'll see if I can switch the flag to a borderless button instead of the icon within a button and see if that helps.

I think it's pretty common for software to offer multiple ways to do the same action, but I appreciate simplicity as well.

**Comment by barefootdeveloper** [comment]
Been a bit busy, but haven't forgoten about this :)

**Comment by 255kb** [comment]
> Been a bit busy, but haven't forgotten about this :)

@barefootdeveloper no hurry 😃, one thing though, I need to publish a new version before August, so this could still be included

**Comment by 255kb** [comment]
One last thing that could make the default response even more obvious would be to always display the flag, even when the drop-down is closed. It could be either blue or grey depending on the currently selected response is the default one or not.

**Comment by aleksey-sh** [comment]
I am relatively new to Mockoon but I like it so far. However this has been quite an annoyance having to drag-and-drop responses constantly just in order to get needed response. This would work nicely if you setup a lot of rules and setup responses in automated fashion. However if you are developing and need to constantly switch between responses to get various combination of use cases, its becoming a bit tedious. Imagine working with 4 or 5 endpoints and  Had to start digging around for a solution and luckily found this thread.

I realize that I maybe a bit late to the game but wanted to throw this solution out just in case it gets some traction. Also, since I am new to the tool and lacking knowledge of all ins and outs, I realize that this may not be an ideal solution but in my mind it makes sense.

So, I see currently there is only one flag option that indicates default response. Default responses and any rules could be disabled by clicking on the flag. This would hide all flags in the drop down as well to indicate that defaults and rules are disabled. Essentially it would switch to respond with currently selected response, kind of WYSIWYG. At this time hovering over items would show flag outlines and by clicking on any of those outlines would enable defaults and rules back.

However this would couple defaults and rules concepts. Unless these two are supposed to work together anyway, the above solution may not be an ideal one but it may spark other thoughts or ideas.

As a long-term investment, concept of response selector may be introduced. You already have two buttons (random and sequential order). It probably will make sense to make it a drop down with options like - "Currently Selected", "Random", "Sequential", "Rule-based" and etc, with ability to add more variations that may fit different use cases.

**Comment by 255kb** [comment]
@aleksey-sh What you are saying make perfect sense. This ticket is more or less about changing the way the default response (no rules matched) is selected: flag click instead of drag and drop.
Drag and drop would be kept as a way to define the order of precedence (you may want a 404 at the top for example). 

There is another ticket open to deal with the "I want to disable the rules and serve this specific response" #498. 
I think your dropdown is a good idea because all these options are related: sequential and random responses already disable the rules. So, we could add one more option "Serve the default response" which would also disable the rules.
