### ISSUE TITLE
When no response match is found, Ignore default response, and use proxy

### ISSUE THREAD

**Issue by ninjaneer164** [mockoon/mockoon#278]
**Is your feature request related to a problem? Please describe.**
Scenario: I have a partially functioning graphql server, and I need to mock a small set of graphql responses. I set up a few responses with rules, which is fine, but I also want to be able to call the actual graphql server if none of the responses match.

In current implementation, if no response match is found, it picks the first one.

**Describe the solution you'd like**
Instead of returning the first (default) response, try to call the proxy, if enabled & defined; return 404 otherwise.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by ninjaneer164** [comment]
@255kb let me know if you have any questions/concerns with this issue.

**Comment by 255kb** [comment]
After investigating a little bit I have the following feeling. It does not feel natural as route responses are selected based on rules, **after** a route has been matched. If your route response n° 1 is returned, it's because you are already under a matched route. Reverting back to the proxy needs to "go up" a level (going out of the matched route) and call the catch-all endpoint. This could add some confusion. I want to keep Mockoon simple to use and easy to understand. And the more it evolves, the more I realize than some features that seem quite straightforward are not very clear for everybody. So I would like to avoid at maximum features that are hidden, implicit, or against the "normal" way it should work (route -> response -> end of request). 
Also, the required implementation would be a little bit awkward and would require a redirect to another URL (something generic like `/pleaseGiveMeTheProxy`), in order to be able to reach the catch-all route `/*`. Then, the proxy would need to forward this request to the proxied server but with the initial URL. Moreover, by doing a redirect we could lose some information from the initial request, like the headers. 

For these reasons, I will close this issue for now. Of course, if there is more interest in this feature I will reevaluate.

**Comment by 255kb** [comment]
> It is unfortunate that this idea has been rejected. I have a similar situation where it would be necessary.

This was implemented, not in the form of a route-level proxy setting but in the form of an option, the ["fallback mode"](https://mockoon.com/docs/latest/route-responses/multiple-responses/#fallback-mode). When activated, it will ignore the default response and serve the next route in the list, and ultimately the proxied server if any.
