### ISSUE TITLE
Easy Mock Same route but diff query string val

### ISSUE THREAD

**Issue by ksuedile** [mockoon/mockoon#303]
Hello,
it is difficult to make two mocks for the same route, i.e : /route?toto=1 & /route?toto=2

i would like to be able to mock easily two responses from the history even if the route is the same

**Comment by 255kb** [comment]
Hi @ksuedile, it is not possible to declare a route with query parameters as they are not part of the route definition (but route params are: `/route/:id`). You can only declare one route `/route` and call it with different query params at runtime. That's why the auto mocking feature does not add them to the route declaration

**Comment by ksuedile** [comment]
hi @255kb , i understand, but would it be possible to add a condition in the mock ?
i guess the gui is writing a nginx conf file.
So something like 'the query string path' (gui) => $args ~ "{the query string path}" (nginx)

**Comment by 255kb** [comment]
It's not using nginx, but Node.js' [Express.js library](https://expressjs.com/en/guide/routing.html) where it is expressly indicated: "Query strings are not part of the route path."

However, if you want to serve different content depending on the query param you could set up two responses in the route with two different rules. 
You can have a look at [this tutorial](https://mockoon.com/tutorial/multiple-route-responses/) which explains how to set this up.

**Comment by ksuedile** [comment]
Ok thanks for your quick reply.
I have seen the tutorial for the Rule, but it cannot make two active mocks at the same time, so it does not help me, unless i misunderstand

**Comment by 255kb** [comment]
What do you mean by two active mocks? 
If I understand what you want to achieve (maybe not :) ), you could: 
- create a route `/route`
- create two status 200 responses in this route
- in each response, go to the rules tab, and set up a different query string rule, like this:
![Screenshot_1](https://user-images.githubusercontent.com/7489814/83004364-debb6c80-a00f-11ea-8628-32f553d22255.png)
![Screenshot_2](https://user-images.githubusercontent.com/7489814/83004368-df540300-a00f-11ea-9348-a9f890ffe240.png)

Each response will be used depending on the query params provided, and you will be able to serve different bodies, headers, etc

**Comment by ksuedile** [comment]
ooohhh, i did not realize that IS the way to achieve what i want !
What a wonderful and complete tool you made.

Yes, i need two 200 responses with different body responses according to the query string.
Now, thanks to your example, i know how to do it.

Thank you a lot for the precisions :)

**Comment by ksuedile** [comment]
another question not relative to the original title of this FR :
would it be possible to have a server version of mockoon ?
I mean a version without GUI or with a remote GUI.
The use would be to be able to use (and if possible create) mocks on a server application hosted on a test server

**Comment by 255kb** [comment]
No problem, your question obviously indicates that some things are not clear enough and that I need to improve the documentation and write more tutorials 👍 

Concerning your last question, a CLI is one of the most requested feature #62 
So, it's on the roadmap, definitely, I just cannot give an ETA. I want to do it right and take the time to deliver something great. I already started refactoring some code in order to prepare for this. 
Also, it will most probably take the form of a NPM package.
