### ISSUE TITLE
Add support for properties containing dots in rules

### ISSUE THREAD

**Issue by sergheev** [mockoon/mockoon#338]
**Describe the bug**
In my application I have route related.role=owner, but when I want to create a rule with query string in mockoon with name: related.role and value: owner
It is not work because I use a dot between related and role, in case of comma it is work as expected.
Please review.

**Screenshots**
![image](https://user-images.githubusercontent.com/33028690/92236748-b2d93e00-eebe-11ea-8b10-c51fc13fa971.png)

**Mockoon version:**
1.9.0

**OS / OS version:**
Windows 10

**Comment by mauriceackel** [comment]
This issue occurs due to the usage of the `object-path` library in the [rule-interpreter](https://github.com/mockoon/commons/blob/17e069eaffd893342b34c42f8dc636e12c8c465b/src/libs/response-rules-interpreter.ts#L68).

Express parses the query parameter `foo.bar=test` into `{ "foo.bar": "test" }`. However, I think the object-path library does not support dots in key names. [Here](https://github.com/mariocasciaro/object-path/issues/67) is an old issue regarding this topic.

I personally think that there is no need to explicitly handle this (i.e. by writing own functionality to retrieve the objects) as even if this would be done, how would the user specify which dot ist part of a key name and which is a legit object delimiter.

@sergheev I would suggest you don't use dots inside the names for your query parameters. IMHO this is not a best practice anyways.

**Comment by 255kb** [comment]
I would have the same reasoning @mauriceackel 
I don't see how to distinguish between an object path and a property containing a dot without introducing some custom syntax. And it's true that I was in a team in the past where properties had dots everywhere and it created some difficulties with several libs in JS and Java (not only object-path). 
So I think we won't do any change for now regarding this issue.

**Comment by 255kb** [comment]
Reopened following several discussions (https://github.com/mockoon/mockoon/discussions/739)
