### ISSUE TITLE
Displayed parsing error pop-up for valid json

### ISSUE THREAD

**Issue by mufiio** [mockoon/mockoon#371]
**Describe the bug**
Since new mockoon version (1.11.0) calling endpoint with header **Content-Type: application/json** results in displaying parsing error pop-up. On version 1.10.0 for exactly the same environment settings pop-up is not displayed.It seems like it's just UI issue on mockoon side, because inside application even due to error, everything is parsing correctly.

**To Reproduce**
Call any endpoint with request header Content-Type: application/json
Route: ```/test```
Response-type: ```200 - OK```
Body: 
```{"userId": 5,"name": "John"}```

**Expected behavior**
Pop-up not displayed.

**Screenshots**
<img width="901" alt="error" src="https://user-images.githubusercontent.com/34597369/99411189-9bbdc000-28f3-11eb-82b6-49c3ad89b305.png">

**Mockoon version:**
1.11.0

**OS / OS version:**
Windows 10, Mac OS Big Sur, Linux Ubuntu 20.04

**Comment by 255kb** [comment]
Since v1.11.0, error reporting has been improved a little bit and most parsing errors are not blocking anymore. Also, the popup you got is a parsing error of the **entering** request's body, not your mock body which is correct. You may want to look at what has been sent to Mockoon by looking at the environment logs ("clock" icon in the upper right corner, [more info in the docs](https://mockoon.com/docs/latest/requests-logging/ )) and try to fix it. 
This error won't stop Mockoon from serving the mock response, but may prevent you from using templating helpers that are fetching part of the entering request's JSON body, like `{{body 'path.to.property'}}`.

**Comment by mufiio** [comment]
Okay, good to know about it. Checked this again based on above information and indeed found the issue on my side. It was caused by the fact that some of the request even though without body had sent Content-Type that was application/json which in that case is not correct approach, hence the error on mockoon side. (Indeed improved :) )
Sorry to bother, can be closed.

**Comment by 255kb** [comment]
Ah yes, this can cause an error too. It was complex to choose between too many errors and not enough. I always hope that I've found the right balance 😄
