### ISSUE TITLE
Faker date formatting not as expected

### ISSUE THREAD

**Issue by didien** [mockoon/mockoon#392]
**Describe the bug**
When using the `{{faker 'date.recent'}}` helper, the expected result is something like `"2020-12-24T03:06:43.847Z"` (as explained in Faker.js' doc) but I'm getting something like `Thu Dec 24 2020 14:22:55 GMT+0100 (Central European Standard Time)`.

**To Reproduce**
Use a template like this one : 
```
{
  "date": "{{ faker 'date.recent'}}"
}
```

**Expected behavior**
I'm expecting an ISO formatted date as vanilla Faker.js would provide it, not a reformatted one.

**Screenshots**
This is the result with the faker helper :
![image](https://user-images.githubusercontent.com/7602689/103097784-b0832700-4608-11eb-9914-698296be5b7f.png)
This is what I'm expecting, and that I get when using this workaround : `{{date '2019' '2020' "yyyy-MM-d'T'HH:mm:ss'Z'"}}`
![image](https://user-images.githubusercontent.com/7602689/103098008-91d16000-4609-11eb-953c-63666ace0f02.png)

**Mockoon version:**
1.11.0

**OS / OS version:**
Mac OS

**Comment by 255kb** [comment]
Mockoon is not reformatting Faker's output, I am curious where you saw the `date.recent` format, I don't see it in [the docs](http://marak.github.io/faker.js/faker.date.html#-static-recent__anchor). In fact, when looking at the [code](https://github.com/Marak/faker.js/blob/master/lib/date.js#L80) it seems that this is the expected output. 

Currently, using Mockoon's own `date` or `now` helpers is the only workaround.

**Comment by sethbro** [comment]
So, since what Faker date functions actually return are `Date` objects, it seems to me that this issue is likely the result of `toString()` being called on that object somewhere in the pipeline.

```
> faker.date.recent()
2022-01-03T20:10:58.020Z

> faker.date.recent().toString()
'Mon Jan 03 2022 11:35:55 GMT-0800 (Pacific Standard Time)'

> faker.date.recent().toISOString()
'2022-01-03T14:36:19.919Z'
```

I've still found no better workaround than those suggested. It might be cool to expose some of [`date-fns` other formatting options](https://date-fns.org/v2.11.1/docs/formatRFC3339), or to allow users to create custom helpers, as has been suggested elsewhere.

**Comment by 255kb** [comment]
@sethbro Probably due to the fact that Handlebars convert helper result to strings. 

Did you have a look at the [`now`](https://mockoon.com/docs/latest/templating/mockoon-helpers/#now) [`date`](https://mockoon.com/docs/latest/templating/mockoon-helpers/#date) helpers? They allow you to get a random date between two boundaries or the current time, and it will format using date-fns syntax.
