### ISSUE TITLE
Resending text with characters such as quotation marks and newlines

### ISSUE THREAD

**Issue by filipebraida** [mockoon/mockoon#397]
I created a template that resends a parameter received via POST to the client. However, the text has quotation marks and line breaks. In my client who gets this message, it seems that he interpreted and in this way resent without escaping.

**Example**:
<img width="1592" alt="Screen Shot 2021-01-11 at 11 52 18" src="https://user-images.githubusercontent.com/2746730/104197185-7769f580-5403-11eb-83fa-f0dea97ce99f.png">

**Mockoon**: 1.11.0
**OS**: MacOS

**Comment by mauriceackel** [comment]
I can reproduce this issue. The main cause is that in the [helper](https://github.com/mockoon/commons/blob/17e069eaffd893342b34c42f8dc636e12c8c465b/src/libs/template-parser.ts#L117), the parsed string value is retuned as a safe string. Hence, there are no escaping like \" or \n left but only the ASCII/UTF-8 characters.

There are different ways to tackle this:
1. Change the helper linked above to return the `SafeString(JSON.stringify(value))` instead of only `SafeString(value)`. This would get back the escaping again. However, it would also return quotes around the value. Hence, this might be **breaking change**!
2. Same as variant one but instead of returning the stringified value by default, there would be an additional property (i.e. `raw`), which is false by default but when it is set true, the stringified result is returned.
3. Add a new helper `stringify`, which either takes an input directly or the result of another helper function and returns the result of `JSON.stringify(<INPUT>)`. However, I'm not quite sure if/how this would work with handlebars (i.e. there might be issues if all parameter values are interpreted as string)

Personally I prefer the second solution as it is clean and does not introduce a breaking change. @255kb Let me know what you think and I can potentially work on a PR for this 🚀
