### ISSUE TITLE
Rendering query parameter in JSON body results in invalid JSON if the query parameter value is a string

### ISSUE THREAD

**Issue by Maritims** [mockoon/mockoon#418]
**Describe the bug**
When you use `{{queryParam 'foo'}} in the response JSON body you may end up with invalid JSON if your foo parameter contains a string value.

A query parameter can occur multiple times in a query string. When it occurs multiple times it's always rendered as a collection in the JSON body, as one would expect. However, if it only occurs once it is rendered without encapsulating quotation. This'll work out of the box if the value is a valid integer, long, double, decimal, float or boolean, because that'll result in valid JSON. If it's none of these it's likely a string, and it'll still be rendered without encapsulating quotation. That will result in invalid JSON.

**To Reproduce**
Steps to reproduce the behavior.
Import the following mock into Mockoon and visit the URLs http://localhost:3000/api?foo=bar and http://localhost:3000/api?foo=bar&foo=baz - You'll see that the request to the first URL results in invalid JSON while the request to the second URL results in valid JSON.

`{
    "source": "mockoon:1.11.0",
    "data": [
        {
            "type": "route",
            "item": {
                "uuid": "",
                "documentation": "",
                "method": "get",
                "endpoint": "api",
                "responses": [
                    {
                        "uuid": "",
                        "body": "[\r\n    {\r\n        \"foo\": {{queryParam 'foo'}}\r\n    }\r\n]",
                        "latency": 0,
                        "statusCode": 200,
                        "label": "Default response",
                        "headers": [
                            {
                                "key": "",
                                "value": ""
                            }
                        ],
                        "filePath": "",
                        "sendFileAsBody": false,
                        "rules": [],
                        "rulesOperator": "OR",
                        "disableTemplating": false
                    }
                ],
                "enabled": true,
                "randomResponse": false
            }
        }
    ]
}`

**Expected behavior**
I expect both URLs to produce valid JSON. The easiest fix would probably be to ensure that the query parameter is encapsulated in quotation marks if it occurs only once, although this would make it hard to mock the return of integers, booleans, floats, decimals, longs, doubles etc. If I could somehow choose how to render it based on a specific condition that'd be great.

**Mockoon version:**
1.11.0

**OS / OS version:**
Windows 10

**Comment by mauriceackel** [comment]
I can reproduce this behavior. The main problem is, that the value type of a query parameter can differ from string, namely if there are multiple parameters with the same name.

Note though that this does not seem to be in the official URI [spec](https://tools.ietf.org/html/rfc3986#section-3.4) and might differ in implementations. However for express, which is used in this project, it seems to result in an array according to the [docs](https://expressjs.com/de/api.html#req.query). Even worse, based on the referenced documentation, the query parameter could even be parsed to an object.

However, those cases are already handled in the template parser, [here](https://github.com/mockoon/commons/blob/17e069eaffd893342b34c42f8dc636e12c8c465b/src/libs/template-parser.ts#L146).

So the issue boils down to not being able to distinguish whether the query parameter is a single value (in which case there might be the need to add quotation marks when using the value in a template) or whether it is an object (in which case no quotation marks would be needed).

I think there are different approaches to circumvent this problem:
1. Make it possible to define a rule so that different templates would be used, depending on wether or not the query parameter is an object. This however would potentially be rather difficult and might be overkill.
2. Add a third parameter to the [queryParam helper](https://github.com/mockoon/commons/blob/17e069eaffd893342b34c42f8dc636e12c8c465b/src/libs/template-parser.ts#L124), potentially named `quoteIfPrimitive`, which can be set to true or false (false bing the default). It the parameter is true and the value type is not array or object, the helper would add quotation marks around the value before returning it.

**Comment by mauriceackel** [comment]
@255kb If you prefer the second alternative, I could work on a PR for this :) However, there also seems to be other issues associated with having multiple parameters with the same name (i.e. #419 ), which might want to be taken into consideration before deciding on which route to go.

**Comment by 255kb** [comment]
@mauriceackel Indeed Express is using [`qs`](https://www.npmjs.com/package/qs#readme) package by default to parse the query params, which allows objects and arrays. 
Also, the `queryParam` helper allows getting an object path like `property.0.anotherProp`. We stringify the node when we found something more complex than a primitive, to allow user to fetch entire parts of the query params object, or entire parts of the body. 
It's true that in the case you encounter a string (and only in this case as other primitives does not have quotes), you may have an "invalid" JSON. 
I see two possible "solutions": 
1. do nothing. Fetching array and objects is only here for convenience purpose and adding quotes around the helper or not should be user's responsibility. Not ideal.
2. as you said, add a new param `addQuotes` to add quotes (for string only, I would say). This implementation would differ from other helpers like `body` and we should add the option there too.
3. always add quotes when it's a string (by using JSON stringify). Again, we would need to align other helpers like `body`, but it's also a breaking change. 

I would hesitate between 3 and 2, with a slight preference for 3 as it feels like the right thing to do: give the JSON representation of the value rather than the value if primitive, and the JSON representation if object or array.

Concerning #419 it's true that it's somehow related. But implementation will differ anyway and fixing here won't have any impact on the other question I think.

**Comment by mauriceackel** [comment]
@255kb I think suggestion 3 would also be fix for #397.

**Comment by mauriceackel** [comment]
One potential issue I see, however, is that all (single) query parameters are always interpreted as string. So if you would have a URL like this: `http://localhost?foo=1&bar=text`, `JSON.stringify(req.query.foo)` would return `"1"`.

I think it will come down to a trade-off between consistency and practicality in the end. I mean from a technical standpoint it is just right that all parameters would be wrapped in quotes as technically they are parsed as strings by express. However, this might raise new usability issues for users if they want to return the value as a number or boolean value for example.

To circumvent this type issue, maybe there could be an optional parameter on the helper `parse` which tries to infer the type of the property first (maybe by doing sth. like `JSON.stringify(JSON.parse(<input>))`)

**Comment by 255kb** [comment]
@mauriceackel I don't think it would fix #397 as it has to do with `SafeString`, but I may be mistaken. 
Concerning the query params, it's true that they are always passed as string. I mixed everything with the body in my previous comment. Body is JSON that has different types of primitives. But query params are always passed as string. So to fix this issue, if we go for solution 3, everything would end up in quotes which in my opinion would be the correct approach. Adding another option to parse or not parse would be overkill I think. 
And we would need to align the `body` helper but only for strings.
