### ISSUE TITLE
Proxy - Disable API prefix forwarding doesn't work

### ISSUE THREAD

**Issue by jtamyrc** [mockoon/mockoon#737]
**Describe the bug**

When I enable proxy mode and remove Prefix, the request to the target URL doesn't remove the prefix.

**To Reproduce**

# mock server1: localhost:3003

![image](https://user-images.githubusercontent.com/98812101/175503858-7765e995-c096-4204-87c8-47d3789e864e.png)

![image](https://user-images.githubusercontent.com/98812101/175504150-864247ea-0d50-45cb-b398-33a25f5ea46b.png)

![image](https://user-images.githubusercontent.com/98812101/175504002-2aae5dda-847f-42c8-8f05-ce71b5f7bb21.png)

# mock server2: localhost:5555

![image](https://user-images.githubusercontent.com/98812101/175504300-6d9820e5-7096-4ba8-8e58-c6dfd1c64f0f.png)

![image](https://user-images.githubusercontent.com/98812101/175504364-47335b19-9c64-416e-8cf4-46d4363f6a91.png)

When I send a POST request to `http://localhost:3003/demo`, it doesn't remove the the prefix `demo` and forward the request to `localhost:5555/demo`

**Mockoon version:**

1.19.0

**OS / OS version:**

Windows 10

**Comment by 255kb** [comment]
This is by design. The "remove prefix" option removes the API prefix that you setup in your mock API: 
![image](https://user-images.githubusercontent.com/7489814/175653183-249f4321-4080-47a7-8aa2-b55bd8ddbd3c.png)

Which means that if your mock 1 has a prefix like `/api`, when calling `http://localhost:3003/api/demo`, it will be forwarded without `/api`: `http://localhost:5005/demo`.
As there is no prefix defined in mock 1, `/demo` is always considered as an endpoint and forwarded "as-is".

I hope this answers your question.

**Comment by jtamyrc** [comment]
Thanks for your reply @255kb 
I understand now.
