### ISSUE TITLE
Mock dynamic JWT token

### ISSUE THREAD

**Issue by erudenko** [mockoon/mockoon#740]
As we create a dynamic replacement for the backend with Mockoon, we need a way to generate a valid JWT token. 

A good example is:
https://www.mocklab.io/docs/response-templating/jwt/

In response we need to generate the JWT like that:

```
{{{jwt maxAge='12 days'}}}
```

**Comment by arouault-til** [comment]
Is there an update on this ?

**Comment by 255kb** [comment]
@arouault-til updates are either visible here or on the [roadmap](https://github.com/orgs/mockoon/projects/9/views/1). If it doesn't move, nothing changed. 
As with other feature requests, I'm open to external help 🙂

**Comment by gbrantzos** [comment]
Hello to all. Latest faker.js version has a relevant [method](https://fakerjs.dev/api/internet.html#jwt) on internet module. Would you consider upgrading faker instead of implementing this feature?

**Comment by 255kb** [comment]
@gbrantzos We just updated to Faker 9.0.0 in version 9. They release too fast 🙈 

This would be indeed a step in the right direction. Though, I'm not sure it will be enough: 
"Please note that this method generates a random signature instead of a valid one."

I will update Faker in upcoming v9.1.0 and I suggest people interested by this feature test and assess if it's enough and if this issue can be closed.

**Comment by 255kb** [comment]
[v9.1.0](https://mockoon.com/releases/9.1.0/) was released with Fakerjs updated to v9.3. It now includes a `jwt` function that you can use like this: 
`{{faker 'internet.jwt'}}`

I would be happy to close this issue if this is enough! Let me know.

**Comment by 255kb** [comment]
> Seems good to me, thanks

I will close it then. Thanks!
