### ISSUE TITLE
Unable to run the latest cli version 2.1.0 with environment file from v1.20.0

### ISSUE THREAD

**Issue by dilaniMaheswaran** [mockoon/mockoon#796]
**Bug Description**

Created some mock apis in the mockoon main app v1.20.0  and located the environment file. Tried loading the file on the latest cli version with docker, it failed with error 

Error: This file is not a valid OpenAPI specification (JSON or YAML v2.0.0
 ›    and v3.0.0) or Mockoon environment: ENOENT: no such file or directory,
 ›   open '-i'

**To Reproduce**

1. Create some mock apis environment in v1.20.0
2. Locate the environment file - right-click on an environment and select "Show in folder".
3. Run the docker mockoon cli

docker run --platform linux/amd64 --mount type=bind,source=/data/test.json,target=/data,readonly -p 3000:3000 mockoon/cli:latest -d data -i 0 -p 3000

**Mockoon version:**
cli version - 2.1.0
main app version - 1.20.0

**OS / OS version:**
Mac OS

**Comment by 255kb** [comment]
Sorry for this. Since [v1.6.0](https://github.com/mockoon/cli/releases/tag/v1.6.0) `-i`/`--index` flag was removed. It should have been a major version instead of a minor. 

To solve this, change the command to `docker run --platform linux/amd64 --mount type=bind,source=/data/test.json,target=/data,readonly -p 3000:3000 mockoon/cli:latest -d data -p 3000`

[Relevant documentation](https://github.com/mockoon/mockoon/tree/main/packages/cli#mockoon-cli-start)

**Comment by dilaniMaheswaran** [comment]
Thank you for the prompt response.

It will be useful and save some time for the devs if docker hub instructions [mockoon/cli](https://hub.docker.com/r/mockoon/cli) are updated as well, as it says --index must be provided when running the container.

**Comment by 255kb** [comment]
Oh true, I completely forgot about this. Will update immediately.
