### ISSUE TITLE
App doesn't close with the standard Command+Q or from the menu bar

### ISSUE THREAD

**Issue by idevelop-app** [mockoon/mockoon#838]
I have the app in the dock, I noticed it didn't close because it will have the dot under the app icon, indicating the app is running, even after a few minutes it will still be running, if I go to Activity Monitor it will be there as well:

<img width="893" alt="image" src="https://user-images.githubusercontent.com/110728525/196940362-0a9a3c00-1f2d-43f3-bcd6-e75bf0f20df1.png">

If I quit it from the Dock it works immediately:

<img width="238" alt="image" src="https://user-images.githubusercontent.com/110728525/196940390-8f86efaa-7ffc-4ef5-8cc3-6f4ee014573b.png">

Command + Q or from the Menu bar doesn't work at all:

<img width="238" alt="image" src="https://user-images.githubusercontent.com/110728525/196940407-e3207f93-8ea6-40b0-918e-1ec7c6e216d4.png">

**Comment by kajweb** [comment]
Actually I don't care if he quits or not, but that affects shutting down the computer

**Comment by 255kb** [comment]
Note for later: relevant documentation on MacOS "recommended" behavior https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app#open-a-window-if-none-are-open-macos

**Comment by idevelop-app** [comment]
Using a MBP with Intel doesn't experience the issue quoting, so far only on M1 devices

**Comment by hasanniz** [comment]
Happening on my 2019 Intel 16" MBP, quitting the app using CMD+Q only closes the window but keeps the app running.

**Comment by 255kb** [comment]
> Happening on my 2019 Intel 16" MBP, quitting the app using CMD+Q only closes the window but keeps the app running.

Not sure this is the issue described here. I am not a mac user but I initially followed Electron's recommended way of closing the application on macOS which is apparently "closing the window but keeping the app running in the dock". 
There are dozens of examples of this on the Internet (see below) and it's apparently the way most app behaves (not only related to Electron). 

https://stackoverflow.com/questions/35008347/electron-close-w-x-vs-right-click-dock-and-quit
https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app#quit-the-app-when-all-windows-are-closed-windows--linux
https://www.electronjs.org/docs/latest/tutorial/macos-dock
https://stackoverflow.com/questions/44316306/how-to-quit-electron-app-on-mac

On a side note, I will soon publish a new release with an update of Electron. I suggest that @idevelop-app retest and confirm the issue is still there.

**Comment by 255kb** [comment]
Could you please re-test with the latest version (v3.0.0)? We updated Electron to v20 and I am curious to see if the app is still affecting the computer shutdown. 

Concerning the behavior of closing the window but keeping the app opened in the dock, I am not sure I want to change this behavior which is the recommended one.

**Comment by 255kb** [comment]
Considering the lack of feedback/interactions, I will close this issue.
