### ISSUE TITLE
Proxied requests does not take into account routes rules

### ISSUE THREAD

**Issue by light1203** [mockoon/mockoon#889]
When using mockoon as a proxy, when using a custom reposnse for a particular route, rules should apply on when the custom response is sent back as a response (instead of proxied response), but instead all request that match the route ar proxied and rules not apllied.

Example:

request:  192.168.1.1/get/command?object=time
route: /get/command
rule: route parameter name=object equals value=time

in that case i expect that only  192.168.1.1/get/command?object=time gets the custom response and all other 
192.168.1.1/get/command request are proxied.

instead all of routes  /get/command are proxied without taking into account rules

Mockoon version : 1.21.1
OS: Win 10 Pro 21H2 19044.2311 (but also win 7 and i think all os versions,since this bug has been around for well over a year)

**Comment by 255kb** [comment]
The proxy mode is only active at the server level, not the route level. And the rules are never involved. 
Which means that when an endpoint exists, the default response, or the response according to the rules will be served if the path matches, and the proxy will not get triggered. If all the rules fail, the default response is always served.
There is already an issue opened for route level proxy based on rules #363. So I guess this issue is a duplicate and I will close it. 

Concerning the rule itself, you are using a query parameter `?object=time`, and not a route parameter (`/route/:param`). So, in your rule setup you should use "Query string" and not "Route params". 

> rule: route parameter name=object equals value=time
